# Generated by Django 4.0.3 on 2022-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppOption',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('value', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'App Options',
            },
        ),
    ]
