# Generated by Django 4.0.3 on 2022-03-12 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('category', models.CharField(choices=[('P', 'POOR'), ('NP', 'NOT POOR'), ('NC', 'NO CARD')], max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Card Categories',
            },
        ),
        migrations.CreateModel(
            name='CardPerson',
            fields=[
                ('card_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('person_photo', models.ImageField(default='default.jpg', upload_to='media/persons/')),
                ('barcode_photo', models.ImageField(default='default.jpg', upload_to='media/barcodes/')),
                ('card_photo', models.ImageField(default='default.jpg', upload_to='media/cards/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='cards.cardcategory')),
            ],
            options={
                'verbose_name_plural': 'Card Persons',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('card_holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guardian', serialize=False, to='cards.cardperson')),
                ('relationship_with_guardian', models.CharField(choices=[('FAT', 'FATHER'), ('MOT', 'MOTHER'), ('HUS', 'HUSBAND'), ('WIF', 'WIFE'), ('BRO', 'BROTHER'), ('SON', 'SON'), ('DAU', 'DAUGHTER'), ('UNC', 'UNCLE'), ('AUN', 'AUNT')], max_length=3)),
                ('guardian_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cards.cardperson')),
            ],
            options={
                'verbose_name_plural': 'Family Members',
            },
        ),
    ]
