# Generated by Django 4.0.3 on 2022-07-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardCategory',
            fields=[
                ('category', models.CharField(default='New discount', max_length=25, primary_key=True, serialize=False, unique=True)),
                ('doctor_fee_discount', models.IntegerField(default=0)),
                ('test_fee_discount', models.IntegerField(default=0)),
                ('medicine_fee_discount', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Card Categories',
            },
        ),
        migrations.CreateModel(
            name='CardPerson',
            fields=[
                ('card_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('person_photo', models.ImageField(default='persons/default.png', upload_to='persons/')),
                ('barcode_photo', models.ImageField(default='default.jpg', upload_to='barcodes/')),
                ('card_pdf', models.FileField(default='default.jpg', upload_to='cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='cards.cardcategory')),
            ],
            options={
                'verbose_name_plural': 'Card Persons',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('card_holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='guardian', serialize=False, to='cards.cardperson')),
                ('relationship_with_guardian', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt')], max_length=8)),
                ('guardian_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('card_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='cards.cardperson')),
            ],
            options={
                'verbose_name_plural': 'Family Members',
            },
        ),
    ]
