# Generated by Django 4.0.3 on 2022-03-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardperson_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardperson',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='cardperson',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
