# Generated by Django 4.0.3 on 2022-03-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_cardperson_birth_date_cardperson_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardperson',
            name='card_photo',
        ),
        migrations.AddField(
            model_name='cardperson',
            name='card_pdf',
            field=models.FileField(default='default.jpg', upload_to='media/cards/'),
        ),
    ]
