# Generated by Django 4.0.3 on 2022-03-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_cardperson_barcode_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardperson',
            name='card_pdf',
            field=models.FileField(default='default.jpg', upload_to='cards/'),
        ),
        migrations.AlterField(
            model_name='cardperson',
            name='person_photo',
            field=models.ImageField(default='default.jpg', upload_to='media/persons/'),
        ),
    ]
