# Generated by Django 4.0.3 on 2022-03-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_cardperson_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardperson',
            name='person_photo',
            field=models.ImageField(default='persons/default.png', upload_to='persons/'),
        ),
    ]
