# Generated by Django 4.0.3 on 2022-03-31 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_cardperson_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardperson',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cardperson',
            name='category',
            field=models.ForeignKey(default='M', on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='cards.cardcategory'),
            preserve_default=False,
        ),
    ]
