# Generated by Django 4.0.3 on 2022-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_cardperson_address_alter_cardperson_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardperson',
            name='barcode_photo',
            field=models.ImageField(default='default.jpg', upload_to='barcodes/'),
        ),
    ]
