# Generated by Django 4.0.3 on 2022-08-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_appointment_doctor_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='serial_no',
            field=models.IntegerField(default=0),
        ),
    ]
