# Generated by Django 4.0.3 on 2022-08-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_appointment_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='serial_no',
            field=models.IntegerField(),
        ),
    ]
