# Generated by Django 4.0.3 on 2022-09-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_appointment_doctor_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(default='default.jpg', upload_to='prescriptions/')),
            ],
        ),
    ]
