# Generated by Django 4.0.3 on 2022-09-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_prescriptionpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_fee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lab_fee',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
