# Generated by Django 4.0.3 on 2022-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=60)),
                ('medical_college', models.CharField(max_length=100)),
                ('mbbs_passing_year', models.DateField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('specialist_at', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_fee', models.IntegerField()),
            ],
        ),
    ]
